#if ZONDERQ_NETWORK_N7_PROBE
using System;
using Cosmos.Kernel.System.Network;
namespace ZonderqOS { internal static class DhcpStageProbe {
 const uint Xid=0x5a4e3701; const ushort ProofEtherType=0x88BA; static byte[] Mac=new byte[6],OfferIp=new byte[4],ServerIp=new byte[4]; static bool Offered,Done; static readonly byte[] Zero={0,0,0,0},Broadcast={255,255,255,255},Proof=Bytes("ZONDERQ_N7_DHCP_CONFIGURED");
 internal static void Run(){if(!NetworkManager.IsEnabled||!NetworkManager.Ready||!NetworkManager.LinkUp){Console.WriteLine("[NETWORK-N7][FAIL] NIC not ready");return;}if(!NetworkManager.SetRawReceiveHandler(OnFrame)){Console.WriteLine("[NETWORK-N7][FAIL] raw RX rejected");return;}Mac=ParseMac(NetworkManager.MacAddress?.ToString()??"");SendDhcp(1,null,null);}
 static void OnFrame(byte[] d,int n){if(Done||n<14+20+8+240||d[12]!=8||d[13]!=0)return;int ip=14,ihl=(d[ip]&15)*4,total=Get16(d,ip+2);if((d[ip]>>4)!=4||ihl<20||ip+total>n||d[ip+9]!=17||Checksum(d,ip,ihl)!=0)return;int u=ip+ihl,ul=Get16(d,u+4);if(Get16(d,u)!=67||Get16(d,u+2)!=68||ul<8+240||u+ul>n)return;int b=u+8;if(d[b]!=2||Get32(d,b+4)!=Xid||!Eq(d,b+28,Mac)||Get32(d,b+236)!=0x63825363)return;int mt=0;byte[] sid=null,mask=null,router=null,dns=null;for(int p=b+240;p<u+ul;){int c=d[p++];if(c==255)break;if(c==0)continue;if(p>=u+ul)break;int l=d[p++];if(p+l>u+ul)break;if(c==53&&l==1)mt=d[p];else if(c==54&&l==4)sid=Slice(d,p,4);else if(c==1&&l==4)mask=Slice(d,p,4);else if(c==3&&l>=4)router=Slice(d,p,4);else if(c==6&&l>=4)dns=Slice(d,p,4);p+=l;}
 if(!Offered&&mt==2&&sid!=null){Copy(d,b+16,OfferIp,0,4);ServerIp=sid;Offered=true;SendDhcp(3,OfferIp,ServerIp);return;}if(Offered&&mt==5&&Eq(d,b+16,OfferIp)&&sid!=null&&Eq(sid,ServerIp)&&mask!=null&&router!=null&&dns!=null){Done=true;SendProof(mask,router,dns);}}
 static void SendDhcp(byte type,byte[] requested,byte[] server){int opt=4+(type==3?12:0)+1,bl=240+opt,ul=8+bl,tl=20+ul;byte[] f=new byte[Math.Max(300,14+tl)];for(int i=0;i<6;i++)f[i]=255;Copy(Mac,0,f,6,6);f[12]=8;f[13]=0;int ip=14;f[ip]=0x45;Put16(f,ip+2,(ushort)tl);Put16(f,ip+4,0x4e37);Put16(f,ip+6,0x4000);f[ip+8]=64;f[ip+9]=17;Copy(Zero,0,f,ip+12,4);Copy(Broadcast,0,f,ip+16,4);Put16(f,ip+10,Checksum(f,ip,20));int u=ip+20;Put16(f,u,68);Put16(f,u+2,67);Put16(f,u+4,(ushort)ul);int b=u+8;f[b]=1;f[b+1]=1;f[b+2]=6;Put32(f,b+4,Xid);Put16(f,b+10,0x8000);Copy(Mac,0,f,b+28,6);Put32(f,b+236,0x63825363);int p=b+240;f[p++]=53;f[p++]=1;f[p++]=type;if(type==3){f[p++]=50;f[p++]=4;Copy(requested,0,f,p,4);p+=4;f[p++]=54;f[p++]=4;Copy(server,0,f,p,4);p+=4;}f[p]=255;NetworkManager.Send(f,f.Length);}
 static void SendProof(byte[] mask,byte[] router,byte[] dns){byte[] f=new byte[96];Copy(ServerIp,0,f,0,4);Copy(Mac,0,f,6,6);f[12]=(byte)(ProofEtherType>>8);f[13]=(byte)(ProofEtherType&255);Copy(Proof,0,f,14,Proof.Length);int p=14+Proof.Length;Copy(OfferIp,0,f,p,4);Copy(mask,0,f,p+4,4);Copy(router,0,f,p+8,4);Copy(dns,0,f,p+12,4);NetworkManager.Send(f,f.Length);}
 static ushort Checksum(byte[] b,int o,int n){uint s=0;for(int i=0;i<n;i+=2)s+=(uint)((b[o+i]<<8)+(i+1<n?b[o+i+1]:0));while((s>>16)!=0)s=(s&65535)+(s>>16);return(ushort)~s;}static bool Eq(byte[] b,int o,byte[] x){for(int i=0;i<x.Length;i++)if(b[o+i]!=x[i])return false;return true;}static bool Eq(byte[] a,byte[] b){if(a.Length!=b.Length)return false;for(int i=0;i<a.Length;i++)if(a[i]!=b[i])return false;return true;}static byte[] Slice(byte[] b,int o,int n){byte[] r=new byte[n];Copy(b,o,r,0,n);return r;}static ushort Get16(byte[] b,int o)=>(ushort)((b[o]<<8)|b[o+1]);static uint Get32(byte[] b,int o)=>(uint)((b[o]<<24)|(b[o+1]<<16)|(b[o+2]<<8)|b[o+3]);static void Put16(byte[] b,int o,ushort v){b[o]=(byte)(v>>8);b[o+1]=(byte)v;}static void Put32(byte[] b,int o,uint v){b[o]=(byte)(v>>24);b[o+1]=(byte)(v>>16);b[o+2]=(byte)(v>>8);b[o+3]=(byte)v;}static void Copy(byte[] s,int so,byte[] d,int o,int n){for(int i=0;i<n;i++)d[o+i]=s[so+i];}static byte[] Bytes(string s){byte[] r=new byte[s.Length];for(int i=0;i<s.Length;i++)r[i]=(byte)s[i];return r;}static byte[] ParseMac(string s){byte[] r=new byte[6];int p=0,v=0,k=0;for(int i=0;i<s.Length&&p<6;i++){char c=s[i];int x=c>='0'&&c<='9'?c-'0':c>='A'&&c<='F'?c-'A'+10:c>='a'&&c<='f'?c-'a'+10:-1;if(x<0)continue;v=(v<<4)|x;if(++k==2){r[p++]=(byte)v;v=0;k=0;}}return r;}
}}
#endif
