#if ZONDERQ_NETWORK_N8_PROBE
using System;
using Cosmos.Kernel.System.Network;
namespace ZonderqOS { internal static class DnsStageProbe {
 const ushort SrcPort=46308,TxId=0x5a38,ProofEtherType=0x88BB; static readonly byte[] LocalIp={10,0,2,15},DnsIp={10,0,2,2},DnsMac=new byte[6],Proof=Bytes("ZONDERQ_N8_DNS_VALIDATED"); static byte[] Mac=new byte[6]; static bool Arp,Done;
 internal static void Run(){if(!NetworkManager.IsEnabled||!NetworkManager.Ready||!NetworkManager.LinkUp){Console.WriteLine("[NETWORK-N8][FAIL] NIC not ready");return;}if(!NetworkManager.SetRawReceiveHandler(OnFrame)){Console.WriteLine("[NETWORK-N8][FAIL] raw RX rejected");return;}Mac=ParseMac(NetworkManager.MacAddress?.ToString()??"");byte[] f=new byte[64];for(int i=0;i<6;i++)f[i]=255;Copy(Mac,0,f,6,6);f[12]=8;f[13]=6;Put16(f,14,1);Put16(f,16,0x0800);f[18]=6;f[19]=4;Put16(f,20,1);Copy(Mac,0,f,22,6);Copy(LocalIp,0,f,28,4);Copy(DnsIp,0,f,38,4);NetworkManager.Send(f,f.Length);}
 static void OnFrame(byte[] d,int n){if(!Arp&&n>=42&&d[12]==8&&d[13]==6&&Get16(d,20)==2&&Eq(d,28,DnsIp)&&Eq(d,38,LocalIp)){Copy(d,22,DnsMac,0,6);Arp=true;SendQuery();return;}if(Done||!Arp||n<54||d[12]!=8||d[13]!=0)return;int ip=14,ihl=(d[ip]&15)*4,total=Get16(d,ip+2);if((d[ip]>>4)!=4||ihl<20||ip+total>n||d[ip+9]!=17||Checksum(d,ip,ihl)!=0||!Eq(d,ip+12,DnsIp)||!Eq(d,ip+16,LocalIp))return;int u=ip+ihl,ul=Get16(d,u+4);if(Get16(d,u)!=53||Get16(d,u+2)!=SrcPort||ul<20||u+ul>n)return;ushort wire=Get16(d,u+6);if(wire==0||UdpChecksum(d,u,ul,DnsIp,LocalIp)!=0)return;int q=u+8;if(Get16(d,q)!=TxId||(Get16(d,q+2)&0x8180)!=0x8180||Get16(d,q+4)!=1||Get16(d,q+6)<1)return;int p=q+12;while(p<u+ul&&d[p]!=0){int l=d[p++];p+=l;}if(p+5>u+ul)return;p+=5;if(p+16>u+ul||Get16(d,p)!=0xc00c||Get16(d,p+2)!=1||Get16(d,p+4)!=1||Get16(d,p+10)!=4)return;byte[] a={10,0,2,42};if(!Eq(d,p+12,a))return;Done=true;SendProof(a);}
 static void SendQuery(){byte[] q=new byte[30];Put16(q,0,TxId);Put16(q,2,0x0100);Put16(q,4,1);int p=12;q[p++]=7;Copy(Bytes("zonderq"),0,q,p,7);p+=7;q[p++]=4;Copy(Bytes("test"),0,q,p,4);p+=4;q[p++]=0;Put16(q,p,1);Put16(q,p+2,1);SendUdp(q);}
 static void SendUdp(byte[] payload){int ul=8+payload.Length,tl=20+ul;byte[] f=new byte[Math.Max(64,14+tl)];Copy(DnsMac,0,f,0,6);Copy(Mac,0,f,6,6);f[12]=8;f[13]=0;int ip=14;f[ip]=0x45;Put16(f,ip+2,(ushort)tl);Put16(f,ip+4,0x4e38);Put16(f,ip+6,0x4000);f[ip+8]=64;f[ip+9]=17;Copy(LocalIp,0,f,ip+12,4);Copy(DnsIp,0,f,ip+16,4);Put16(f,ip+10,Checksum(f,ip,20));int u=ip+20;Put16(f,u,SrcPort);Put16(f,u+2,53);Put16(f,u+4,(ushort)ul);Copy(payload,0,f,u+8,payload.Length);ushort c=UdpChecksum(f,u,ul,LocalIp,DnsIp);Put16(f,u+6,c==0?(ushort)0xffff:c);NetworkManager.Send(f,f.Length);}
 static void SendProof(byte[] a){byte[] f=new byte[64];Copy(DnsMac,0,f,0,6);Copy(Mac,0,f,6,6);f[12]=(byte)(ProofEtherType>>8);f[13]=(byte)(ProofEtherType&0xff);Copy(Proof,0,f,14,Proof.Length);Copy(a,0,f,14+Proof.Length,4);NetworkManager.Send(f,f.Length);}
 static ushort UdpChecksum(byte[] b,int o,int n,byte[] s,byte[] d){uint x=Words(s,0,4)+Words(d,0,4)+17+(uint)n+Words(b,o,n);while((x>>16)!=0)x=(x&65535)+(x>>16);return(ushort)~x;}static ushort Checksum(byte[] b,int o,int n){uint x=Words(b,o,n);while((x>>16)!=0)x=(x&65535)+(x>>16);return(ushort)~x;}static uint Words(byte[] b,int o,int n){uint s=0;for(int i=0;i<n;i+=2)s+=(uint)((b[o+i]<<8)+(i+1<n?b[o+i+1]:0));return s;}static bool Eq(byte[] b,int o,byte[] x){if(o<0||o+x.Length>b.Length)return false;for(int i=0;i<x.Length;i++)if(b[o+i]!=x[i])return false;return true;}static ushort Get16(byte[] b,int o)=>(ushort)((b[o]<<8)|b[o+1]);static void Put16(byte[] b,int o,ushort v){b[o]=(byte)(v>>8);b[o+1]=(byte)v;}static void Copy(byte[] s,int so,byte[] d,int o,int n){for(int i=0;i<n;i++)d[o+i]=s[so+i];}static byte[] Bytes(string s){byte[] r=new byte[s.Length];for(int i=0;i<s.Length;i++)r[i]=(byte)s[i];return r;}static byte[] ParseMac(string s){byte[] r=new byte[6];int p=0,v=0,k=0;for(int i=0;i<s.Length&&p<6;i++){char c=s[i];int x=c>='0'&&c<='9'?c-'0':c>='A'&&c<='F'?c-'A'+10:c>='a'&&c<='f'?c-'a'+10:-1;if(x<0)continue;v=(v<<4)|x;if(++k==2){r[p++]=(byte)v;v=0;k=0;}}return r;}
}}
#endif