#if ZONDERQ_NETWORK_N5_PROBE
using System;
using Cosmos.Kernel.System.Network;
namespace ZonderqOS {
internal static class IcmpStageProbe {
 const ushort Id=0x5a35, Seq=1, ProofEtherType=0x88B8; static readonly byte[] LocalIp={10,0,2,15},PeerIp={10,0,2,2},PeerMac=new byte[6],Payload=Bytes("ZONDERQ_N5_ICMP_ECHO"),Proof=Bytes("ZONDERQ_N5_ICMP_VALIDATED"); static byte[] LocalMac=new byte[6]; static bool ArpResolved,Done;
 internal static void Run(){if(!NetworkManager.IsEnabled||!NetworkManager.Ready||!NetworkManager.LinkUp){Console.WriteLine("[NETWORK-N5][FAIL] NIC not ready");return;}if(!NetworkManager.SetRawReceiveHandler(OnFrame)){Console.WriteLine("[NETWORK-N5][FAIL] raw RX rejected");return;}LocalMac=ParseMac(NetworkManager.MacAddress?.ToString()??"");byte[] f=new byte[64];for(int i=0;i<6;i++)f[i]=255;Copy(LocalMac,0,f,6,6);f[12]=8;f[13]=6;Put16(f,14,1);Put16(f,16,0x0800);f[18]=6;f[19]=4;Put16(f,20,1);Copy(LocalMac,0,f,22,6);Copy(LocalIp,0,f,28,4);Copy(PeerIp,0,f,38,4);NetworkManager.Send(f,f.Length);}
 static void OnFrame(byte[] d,int n){if(n<14||d.Length<n)return;if(!ArpResolved&&n>=42&&d[12]==8&&d[13]==6&&Get16(d,20)==2&&Eq(d,28,PeerIp)&&Eq(d,38,LocalIp)){Copy(d,22,PeerMac,0,6);ArpResolved=true;SendEcho();return;}if(Done||!ArpResolved||n<42||d[12]!=8||d[13]!=0)return;int o=14,ihl=(d[o]&15)*4,total=Get16(d,o+2);if((d[o]>>4)!=4||ihl<20||total<ihl+8||o+total>n||d[o+9]!=1||!Eq(d,o+12,PeerIp)||!Eq(d,o+16,LocalIp)||Checksum(d,o,ihl)!=0)return;int ic=o+ihl,iclen=total-ihl;if(d[ic]!=0||d[ic+1]!=0||Get16(d,ic+4)!=Id||Get16(d,ic+6)!=Seq||Checksum(d,ic,iclen)!=0||iclen!=8+Payload.Length)return;for(int i=0;i<Payload.Length;i++)if(d[ic+8+i]!=Payload[i])return;Done=true;SendProof();}
 static void SendEcho(){int il=8+Payload.Length,ip=20+il;byte[] f=new byte[Math.Max(64,14+ip)];Copy(PeerMac,0,f,0,6);Copy(LocalMac,0,f,6,6);f[12]=8;f[13]=0;int o=14;f[o]=0x45;Put16(f,o+2,(ushort)ip);Put16(f,o+4,0x4e35);Put16(f,o+6,0x4000);f[o+8]=64;f[o+9]=1;Copy(LocalIp,0,f,o+12,4);Copy(PeerIp,0,f,o+16,4);Put16(f,o+10,Checksum(f,o,20));int ic=o+20;f[ic]=8;Put16(f,ic+4,Id);Put16(f,ic+6,Seq);Copy(Payload,0,f,ic+8,Payload.Length);Put16(f,ic+2,Checksum(f,ic,il));NetworkManager.Send(f,f.Length);}
 static void SendProof(){byte[] f=new byte[64];Copy(PeerMac,0,f,0,6);Copy(LocalMac,0,f,6,6);f[12]=(byte)(ProofEtherType>>8);f[13]=(byte)(ProofEtherType&255);Copy(Proof,0,f,14,Proof.Length);NetworkManager.Send(f,f.Length);}
 static ushort Checksum(byte[] b,int o,int n){uint s=0;for(int i=0;i<n;i+=2)s+=(uint)((b[o+i]<<8)+(i+1<n?b[o+i+1]:0));while((s>>16)!=0)s=(s&65535)+(s>>16);return(ushort)~s;} static bool Eq(byte[] b,int o,byte[] x){for(int i=0;i<x.Length;i++)if(b[o+i]!=x[i])return false;return true;}static ushort Get16(byte[] b,int o)=>(ushort)((b[o]<<8)|b[o+1]);static void Put16(byte[] b,int o,ushort v){b[o]=(byte)(v>>8);b[o+1]=(byte)(v&255);}static void Copy(byte[] s,int so,byte[] d,int o,int n){for(int i=0;i<n;i++)d[o+i]=s[so+i];}static byte[] Bytes(string s){byte[] r=new byte[s.Length];for(int i=0;i<s.Length;i++)r[i]=(byte)s[i];return r;}static byte[] ParseMac(string s){byte[] r=new byte[6];int p=0,v=0,k=0;for(int i=0;i<s.Length&&p<6;i++){char c=s[i];int x=c>='0'&&c<='9'?c-'0':c>='A'&&c<='F'?c-'A'+10:c>='a'&&c<='f'?c-'a'+10:-1;if(x<0)continue;v=(v<<4)|x;if(++k==2){r[p++]=(byte)v;v=0;k=0;}}return r;}
}}
#endif
