#if ZONDERQ_NETWORK_N9_PROBE
using System;
using Cosmos.Kernel.System.Network;
namespace ZonderqOS { internal static class TcpStageProbe {
 const ushort SrcPort=46309,DstPort=8080,ProofEtherType=0x88BC; const uint ClientIsn=0x5a390001; static readonly byte[] LocalIp={10,0,2,15},PeerIp={10,0,2,2},PeerMac=new byte[6],ClientData=Bytes("ZONDERQ_N9_CLIENT"),ServerData=Bytes("ZONDERQ_N9_SERVER"),Proof=Bytes("ZONDERQ_N9_TCP_VALIDATED"); static byte[] Mac=new byte[6]; static int State; static uint PeerNext;
 internal static void Run(){if(!NetworkManager.IsEnabled||!NetworkManager.Ready||!NetworkManager.LinkUp){Console.WriteLine("[NETWORK-N9][FAIL] NIC not ready");return;}if(!NetworkManager.SetRawReceiveHandler(OnFrame)){Console.WriteLine("[NETWORK-N9][FAIL] raw RX rejected");return;}Mac=ParseMac(NetworkManager.MacAddress?.ToString()??"");SendArp();}
 static void SendArp(){byte[] f=new byte[64];for(int i=0;i<6;i++)f[i]=255;Copy(Mac,0,f,6,6);f[12]=8;f[13]=6;Put16(f,14,1);Put16(f,16,0x0800);f[18]=6;f[19]=4;Put16(f,20,1);Copy(Mac,0,f,22,6);Copy(LocalIp,0,f,28,4);Copy(PeerIp,0,f,38,4);NetworkManager.Send(f,f.Length);}
 static void OnFrame(byte[] d,int n){if(State==0&&n>=42&&d[12]==8&&d[13]==6&&Get16(d,20)==2&&Eq(d,28,PeerIp)&&Eq(d,38,LocalIp)){Copy(d,22,PeerMac,0,6);State=1;SendTcp(ClientIsn,0,0x02,null);return;}if(State<1||State>5||n<54||d[12]!=8||d[13]!=0)return;int ip=14,ihl=(d[ip]&15)*4,total=Get16(d,ip+2);if((d[ip]>>4)!=4||ihl<20||ip+total>n||d[ip+9]!=6||Checksum(d,ip,ihl)!=0||!Eq(d,ip+12,PeerIp)||!Eq(d,ip+16,LocalIp))return;int t=ip+ihl,th=((d[t+12]>>4)&15)*4;if(th<20||t+th>ip+total||Get16(d,t)!=DstPort||Get16(d,t+2)!=SrcPort||TcpChecksum(d,t,total-ihl,PeerIp,LocalIp)!=0)return;uint seq=Get32(d,t+4),ack=Get32(d,t+8);byte flags=d[t+13];int pl=total-ihl-th;
 if(State==1){if((flags&0x12)!=0x12||ack!=ClientIsn+1)return;PeerNext=seq+1;State=2;SendTcp(ClientIsn+1,PeerNext,0x18,ClientData);return;}
 if(State==2){if((flags&0x18)!=0x18||seq!=PeerNext||ack!=ClientIsn+1+(uint)ClientData.Length||pl!=ServerData.Length||!Eq(d,t+th,ServerData))return;PeerNext+=(uint)ServerData.Length;State=3;SendTcp(ClientIsn+1+(uint)ClientData.Length,PeerNext,0x11,null);return;}
 if(State==3){if((flags&0x10)==0||ack!=ClientIsn+2+(uint)ClientData.Length)return;if((flags&0x01)==0)return;if(seq!=PeerNext)return;PeerNext++;State=4;SendTcp(ClientIsn+2+(uint)ClientData.Length,PeerNext,0x10,null);SendProof();State=5;}
 }
 static void SendTcp(uint seq,uint ack,byte flags,byte[] payload){int pn=payload==null?0:payload.Length,tn=20+pn,tl=20+tn;byte[] f=new byte[Math.Max(64,14+tl)];Copy(PeerMac,0,f,0,6);Copy(Mac,0,f,6,6);f[12]=8;f[13]=0;int ip=14;f[ip]=0x45;Put16(f,ip+2,(ushort)tl);Put16(f,ip+4,0x4e39);Put16(f,ip+6,0x4000);f[ip+8]=64;f[ip+9]=6;Copy(LocalIp,0,f,ip+12,4);Copy(PeerIp,0,f,ip+16,4);Put16(f,ip+10,Checksum(f,ip,20));int t=ip+20;Put16(f,t,SrcPort);Put16(f,t+2,DstPort);Put32(f,t+4,seq);Put32(f,t+8,ack);f[t+12]=0x50;f[t+13]=flags;Put16(f,t+14,4096);if(pn>0)Copy(payload,0,f,t+20,pn);ushort c=TcpChecksum(f,t,tn,LocalIp,PeerIp);Put16(f,t+16,c==0?(ushort)0xffff:c);NetworkManager.Send(f,f.Length);}
 static void SendProof(){byte[] f=new byte[64];Copy(PeerMac,0,f,0,6);Copy(Mac,0,f,6,6);f[12]=(byte)(ProofEtherType>>8);f[13]=(byte)ProofEtherType;Copy(Proof,0,f,14,Proof.Length);NetworkManager.Send(f,f.Length);}
 static ushort TcpChecksum(byte[] b,int o,int n,byte[] s,byte[] d){uint x=Words(s,0,4)+Words(d,0,4)+6+(uint)n+Words(b,o,n);while((x>>16)!=0)x=(x&65535)+(x>>16);return(ushort)~x;}static ushort Checksum(byte[] b,int o,int n){uint x=Words(b,o,n);while((x>>16)!=0)x=(x&65535)+(x>>16);return(ushort)~x;}static uint Words(byte[] b,int o,int n){uint s=0;for(int i=0;i<n;i+=2)s+=(uint)((b[o+i]<<8)+(i+1<n?b[o+i+1]:0));return s;}static bool Eq(byte[] b,int o,byte[] x){if(o<0||o+x.Length>b.Length)return false;for(int i=0;i<x.Length;i++)if(b[o+i]!=x[i])return false;return true;}static ushort Get16(byte[] b,int o)=>(ushort)((b[o]<<8)|b[o+1]);static uint Get32(byte[] b,int o)=>(uint)((b[o]<<24)|(b[o+1]<<16)|(b[o+2]<<8)|b[o+3]);static void Put16(byte[] b,int o,ushort v){b[o]=(byte)(v>>8);b[o+1]=(byte)v;}static void Put32(byte[] b,int o,uint v){b[o]=(byte)(v>>24);b[o+1]=(byte)(v>>16);b[o+2]=(byte)(v>>8);b[o+3]=(byte)v;}static void Copy(byte[] s,int so,byte[] d,int o,int n){for(int i=0;i<n;i++)d[o+i]=s[so+i];}static byte[] Bytes(string s){byte[] r=new byte[s.Length];for(int i=0;i<s.Length;i++)r[i]=(byte)s[i];return r;}static byte[] ParseMac(string s){byte[] r=new byte[6];int p=0,v=0,k=0;for(int i=0;i<s.Length&&p<6;i++){char c=s[i];int x=c>='0'&&c<='9'?c-'0':c>='A'&&c<='F'?c-'A'+10:c>='a'&&c<='f'?c-'a'+10:-1;if(x<0)continue;v=(v<<4)|x;if(++k==2){r[p++]=(byte)v;v=0;k=0;}}return r;}
}}
#endif
