<Project Sdk="Cosmos.Sdk/3.0.82">

  <PropertyGroup>
    <CosmosEnableStorage>true</CosmosEnableStorage>
    <CosmosEnableNetwork>true</CosmosEnableNetwork>
    <CosmosEnableGraphics>true</CosmosEnableGraphics>
    <CosmosEnableMouse>true</CosmosEnableMouse>
    <CosmosEnableKeyboard>true</CosmosEnableKeyboard>
    <CosmosKernelClass>ZonderqOS.Kernel</CosmosKernelClass>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cosmos.Kernel" Version="3.0.82" />
    <PackageReference Include="Cosmos.Kernel.System" Version="3.0.82" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="source/GUI/Icons/Assets/*.png">
      <LogicalName>Icons.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="source/Wallpapers/*.png">
      <LogicalName>Wallpapers.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
